"<h1> Shooter OS (Full) </h1>\n"
"<iframe src=\"https://scratch.mit.edu/projects/437800354/embed\" allowtransparency=\"true\" width=\"485\" height=\"402\" frameborder=\"0\" scrolling=\"no\" allowfullscreen></iframe>\n"
"<h1> Shooter OS (Beta) </h1>\n"
"<iframe src=\"https://scratch.mit.edu/projects/437378284/embed\" allowtransparency=\"true\" width=\"485\" height=\"402\" frameborder=\"0\" scrolling=\"no\" allowfullscreen></iframe>\n"
"<h5> Controls and stuff of the Shooter. OS Readme </h5>"